djangoApp/blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView


urlpatterns = [
	path('',PostListView.as_view(), name='Blog-Home'),
	path('post/<int:pk>',PostDetailView.as_view(), name='post-detail'),
	path('post/new',PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/update',PostUpdateView.as_view(), name='post-update'),
	path('post/<int:pk>/delete',PostDeleteView.as_view(), name='post-delete'),
	path('user/<str:username>',UserPostListView.as_view(), name='user-posts'),
	path('about/',views.about, name='Blog-About'),
	]

djangoApp/singleStore/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    BrandView,
    UserOrdersView,
    OrderDashboardView,
    InvoiceDashboardView,
    ShipmentDashboardView,
    RefundDashboardView,
    ViewItems,
    ViewCustomers
)

app_name = 'singleStore'

urlpatterns = [
    path('', HomeView.as_view(), name='store-home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('category/<str:slug>',CategoryView.as_view(), name='by_category'),
    path('orders/',UserOrdersView.as_view(), name='user-orders'),
    path('brand/<str:slug>',BrandView.as_view(), name='by_brand'),
    path('sales_orders/',OrderDashboardView.as_view(), name='sales-orders'),
    path('update_order/<str:pk>/', views.updateOrder, name="update_order"),
    path('generate_invoice/<str:pk>/', views.invoiceOrder, name="generate_invoice"),
    path('sales_invoices/',InvoiceDashboardView.as_view(), name='sales-invoices'),
    path('view_invoice/<str:pk>/', views.viewInvoice, name="view_invoice"),
    path('view_order_invoice/<str:ref_code>/', views.customerViewInvoice, name="customer_view_invoice"),
    path('generate_shipment/<str:pk>/', views.ShipOrder, name="generate_shipment"),
    path('sales_shipments/',ShipmentDashboardView.as_view(), name='sales-shipments'),
    path('view_shipment/<str:pk>/', views.viewShipment, name="view_shipment"),
    path('request_refund/<str:ref_code>/', views.RequestRefund, name="request_refund"),
    path('generate_refund/<str:pk>/', views.RefundOrder, name="generate_refund"),
    path('sales_refunds/',RefundDashboardView.as_view(), name='sales-refunds'),
    path('view_refund/<str:pk>/', views.viewRefund, name="view_refund"),
    path('view_items/', ViewItems.as_view(),name="view_items"),
    path('update_item/<str:pk>/', views.updateItem, name="update_item"),
    path('view_invoices/<str:ref_code>', views.viewInvoices, name="view_invoices"),
    path('view_shipments/<str:ref_code>', views.viewShipments, name="view_shipments"),
    path('view_refunds/<str:ref_code>', views.viewRefunds, name="view_refunds"),
    path('order_invoices/<str:ref_code>', views.viewInvoicesCustomers, name="order_invoices"),
    path('order_shipments/<str:ref_code>', views.viewShipmentsCustomers, name="order_shipments"),
    path('order_refunds/<str:ref_code>', views.viewRefundsCustomers, name="order_refunds"),
    path('customers/',ViewCustomers.as_view(), name='view-customers'),
    path('create_item/', views.createItem, name="create_item"),
]

djangoApp/store/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    DefaultHomeView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    BrandView,
    UserOrdersView,
    OrderDashboardView,
    InvoiceDashboardView,
    ShipmentDashboardView,
    RefundDashboardView,
    ViewItems,
    ViewCustomers
)

app_name = 'store'

urlpatterns = [
    path('', DefaultHomeView.as_view(), name='store-default-home'),
    path('<str:store_slug>/home', HomeView.as_view(), name='store-home'),
    path('<str:store_slug>/checkout/', CheckoutView.as_view(), name='checkout'),
    path('<str:store_slug>/order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('<str:store_slug>/product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('<str:store_slug>/add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('<str:store_slug>/add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('<str:store_slug>/remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('<str:store_slug>/remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('<str:store_slug>/payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('category/<str:slug>',CategoryView.as_view(), name='by_category'),
    path('orders/',UserOrdersView.as_view(), name='user-orders'),
    path('brand/<str:slug>',BrandView.as_view(), name='by_brand'),
    path('sales_orders/',OrderDashboardView.as_view(), name='sales-orders'),
    path('update_order/<str:pk>/', views.updateOrder, name="update_order"),
    path('generate_invoice/<str:pk>/', views.invoiceOrder, name="generate_invoice"),
    path('sales_invoices/',InvoiceDashboardView.as_view(), name='sales-invoices'),
    path('view_invoice/<str:pk>/', views.viewInvoice, name="view_invoice"),
    path('view_order_invoice/<str:ref_code>/', views.customerViewInvoice, name="customer_view_invoice"),
    path('generate_shipment/<str:pk>/', views.ShipOrder, name="generate_shipment"),
    path('sales_shipments/',ShipmentDashboardView.as_view(), name='sales-shipments'),
    path('view_shipment/<str:pk>/', views.viewShipment, name="view_shipment"),
    path('request_refund/<str:ref_code>/', views.RequestRefund, name="request_refund"),
    path('generate_refund/<str:pk>/', views.RefundOrder, name="generate_refund"),
    path('sales_refunds/',RefundDashboardView.as_view(), name='sales-refunds'),
    path('view_refund/<str:pk>/', views.viewRefund, name="view_refund"),
    path('view_items/', ViewItems.as_view(),name="view_items"),
    path('update_item/<str:pk>/', views.updateItem, name="update_item"),
    path('view_invoices/<str:ref_code>', views.viewInvoices, name="view_invoices"),
    path('view_shipments/<str:ref_code>', views.viewShipments, name="view_shipments"),
    path('view_refunds/<str:ref_code>', views.viewRefunds, name="view_refunds"),
    path('order_invoices/<str:ref_code>', views.viewInvoicesCustomers, name="order_invoices"),
    path('order_shipments/<str:ref_code>', views.viewShipmentsCustomers, name="order_shipments"),
    path('order_refunds/<str:ref_code>', views.viewRefundsCustomers, name="order_refunds"),
    path('customers/',ViewCustomers.as_view(), name='view-customers'),
    path('create_item/', views.createItem, name="create_item"),
]

djangoApp/users/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager

#class User(AbstractUser):
#	username = None
#	email = models.EmailField(_('email address'), unique=True)

#	USERNAME_FIELD = 'email'
#	REQUIRED_FIELDS = []

#	objects = CustomUserManager()

#	def __str__(self):
#		return self.email

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone_number = models.CharField(max_length = 15, blank = True)
	image = models.ImageField(default = 'profile_pics/default.png', upload_to = 'profile_pics')
	def __str__(self):
		return f'{self.user.username} Profile'

djangoApp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	full_name = forms.CharField(max_length=255)
	#username = email
	class Meta:
		model = User
		fields = ['email','full_name','password1','password2']

class UserUpdateForm(forms.ModelForm):
        email = forms.EmailField()
        class Meta:
                model = User
                fields = ['email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['phone_number','image']

djangoApp/users/views.py
from django.shortcuts import render, redirect
#from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth.models import User

def register(request):
	if request.method == "POST":
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			#user = form.save()
			print(form.data)
			username = form.cleaned_data.get('email')
			if User.objects.filter(username = username):
				messages.error(request, f'The email address "{username}" is already registered.')
				return redirect('register')
			email = form.cleaned_data.get('email')
			full_name = form.cleaned_data.get('full_name')
			password = form.cleaned_data.get('password1')
			user = User(username = username, email = email, first_name = full_name)
			user.set_password(password)
			user.save()
			group = Group.objects.get(name='customer')
			user.groups.add(group)
			messages.success(request, f'Successfully created an account for { email }. Log in Now!')
			return redirect ('login')
		else:
			messages.warning(request, f'There was an error!')
	else:
		form = UserRegisterForm()
	return render(request,'users/register.html', {'form':form})

@login_required
def profile(request):
	return render(request, 'users/profile.html')

def profileUpdate(request):
        if request.method == "POST":
#                u_form = UserUpdateForm(request.POST, instance=request.user)
#                p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
                u_form = UserUpdateForm(request.POST, instance=request.user)
                p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

                if u_form.is_valid and p_form.is_valid:
                        u_form.save()
                        p_form.save()
                        messages.success(request, f'Your profile has been updated!')
                        return redirect ('profile')
                else:
                        messages.warning(request, f'There was an error!')

        else:
                u_form = UserUpdateForm(instance=request.user)
                p_form = ProfileUpdateForm()

        context = {
                'u_form':u_form,
                'p_form':p_form
        }
        return render(request, 'users/profileUpdate.html',context)

djangoApp/users/templates/users/login.html
{% extends "store/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

	<div class= "login mx-auto">
	<div class= "card card-body">
                <form method= "POST">
                        {% csrf_token %}
			{{ form.non_field_errors }}
                        <fieldset class= "form-group">
			<legend class= "border-bottom mb-3">Login</legend>
			<div class="fieldWrapper mt-3">
				{{ form.username.errors }}
                		<div class="input-group">
                  			<input type='text' placeholder='Email' id='username' name='username' class='form-control' />
                		</div>
			</div>
			<div class="fieldWrapper mt-4 mb-3">
				{{ form.password.errors }}
                		<div class="input-group">
                  			<input type='password' placeholder='Password' id='password' name='password' class='form-control' />
                		</div>
                                        <!--<input type="checkbox" onclick="showPassword()"><small class="text-muted ml-1">Show Password</small>-->
			</div>
			</fieldset>
                        <div class= "form-group">
                                <button class= "btn btn-outline-info" type= "submit">Login</button>
                        </div>
		</form>
                <div class= "border-top pt-3 mt-3">
                        <small class= "text-muted">Forgot you password?<a class ="ml-1" href= "{% url 'reset_password' %}">Reset Password</a></small><br/>
                        <small class= "text-muted">Need an account? <a class= "ml-1"  href= "{% url 'register' %}">Sign Up Now</a></small><br/>
                </div>
	</div>
	</div>
{% endblock content %}

djangoApp/users/templates/users/logout.html
{% extends "store/base.html" %}

{% block content %}
    <div class="logout">
	<h2>You have been logged out.</h2>
	<div class ="border-top pt-3">
		<a href ="{% url 'login' %}">Login back in</a>
	</div>
    </div>

{% endblock content %}

djangoApp/users/templates/users/password_reset.html
{% extends "store/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class = "login mx-auto">
	<div class= "card card-body">
		<legend class= "border-bottom mb-3">Reset Your Password</legend>
		<p>Enter your email address below and we'll send you instructions to reset your password.</p>
		<form method = "post">
    			{%csrf_token%}
    			{{form|crispy}}
			<div class= "form-group">
				<button class= "btn btn-outline-info" type= "submit">Confirm</button>
			</div>
		</form>
	</div>
</div>
{% endblock content %}

djangoApp/users/templates/users/password_reset_complete.html
{% extends "store/base.html" %}

{% block content %}
<div class = "login mx-auto">
        <div class= "card card-body">
                <legend class= "border-bottom mb-3">Password Reset Successfully</legend>
                <p>Your password has been reset successfully.</p>
                <p><a href ="{% url 'login' %}">Login</a> to your account.</p>
        </div>
</div>
{% endblock content %}

djangoApp/users/templates/users/password_reset_confirm.html
{% extends "store/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class = "login mx-auto">
        <div class= "card card-body">
                <legend class= "border-bottom mb-3">Reset Your Password</legend>
                <p>Enter your new password.</p>
                <form method = "post">
                        {%csrf_token%}
                        {{form|crispy}}
                        <div class= "form-group">
                                <button class= "btn btn-outline-info" type= "submit">Confirm</button>
                        </div>
                </form>
        </div>
</div>
{% endblock content %}

djangoApp/users/templates/users/password_reset_sent.html
{% extends "store/base.html" %}

{% block content %}
<div class = "login mx-auto">
        <div class= "card card-body">
                <legend class= "border-bottom mb-3">Password Reset Link Sent</legend>
                <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
		<p>If you don’t receive an email:<br/>
		1. Please make sure you’ve entered the address you registered with us.
		2. Please check your spam/junk folder.<br/></p>
		<p><a href ="{% url 'reset_password' %}">Click here</a> to go back to the forgotten passwords page.</p>
        </div>
</div>
{% endblock content %}

djangoApp/users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
  <div class="media mb-4">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{user.username}}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
    <a href="{% url 'profileUpdate' %}" class="btn btn-outline-info" role="button">Update Profile</a>
    <a href="{% url 'user-posts' user.username %}" class="btn btn-outline-info" role="button">View Posts</a>
    <a href="{% url 'store:user-orders'  %}" class="btn btn-outline-info" role="button">View Orders (MultiStore)</a>
    <a href="{% url 'singleStore:user-orders'  %}" class="btn btn-outline-info" role="button">View Orders (SingleStore)</a>
</div>

{% endblock content %}

djangoApp/users/templates/users/profileUpdate.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{user.username}}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
  <form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class = "form-group">
      <legend class = "border-bottom mb-4">Update Profile Info</legend>
      {{ u_form|crispy }}
      {{ p_form|crispy }}
    </fieldset>
    <div class ="form-group">
      <button class ="btn btn-outline-info" type ="submit">Update</button>
    </div>
   </form>
</div>
{% endblock content %}

djangoApp/users/templates/users/register.html
{% extends "store/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

        <div class ="register mx-auto">
        <div class = "card card-body">
		<form method = "POST">
			{% csrf_token %}
			<fieldset class = "form-group">
				<legend class = "border-bottom mb-4"> Register Now</legend>
				{{ form|crispy }}
			</fieldset>
			<div class ="form-group">
				<button class ="btn btn-outline-info" type ="submit">Sign Up</button>
			</div>
		</form>
		<div class ="border-top pt-3">
			<small class ="text-muted">Already have an account? <a class="ml-2"  href ="#">Sign In</a></small>
		</div>
        </div>
	</div>

{% endblock content %}