djangoApp/blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView


urlpatterns = [
	path('',PostListView.as_view(), name='Blog-Home'),
	path('post/<int:pk>',PostDetailView.as_view(), name='post-detail'),
	path('post/new',PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/update',PostUpdateView.as_view(), name='post-update'),
	path('post/<int:pk>/delete',PostDeleteView.as_view(), name='post-delete'),
	path('user/<str:username>',UserPostListView.as_view(), name='user-posts'),
	path('about/',views.about, name='Blog-About'),
	]

djangoApp/singleStore/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    BrandView,
    UserOrdersView,
    OrderDashboardView,
    InvoiceDashboardView,
    ShipmentDashboardView,
    RefundDashboardView,
    ViewItems,
    ViewCustomers
)

app_name = 'singleStore'

urlpatterns = [
    path('', HomeView.as_view(), name='store-home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('category/<str:slug>',CategoryView.as_view(), name='by_category'),
    path('orders/',UserOrdersView.as_view(), name='user-orders'),
    path('brand/<str:slug>',BrandView.as_view(), name='by_brand'),
    path('sales_orders/',OrderDashboardView.as_view(), name='sales-orders'),
    path('update_order/<str:pk>/', views.updateOrder, name="update_order"),
    path('generate_invoice/<str:pk>/', views.invoiceOrder, name="generate_invoice"),
    path('sales_invoices/',InvoiceDashboardView.as_view(), name='sales-invoices'),
    path('view_invoice/<str:pk>/', views.viewInvoice, name="view_invoice"),
    path('view_order_invoice/<str:ref_code>/', views.customerViewInvoice, name="customer_view_invoice"),
    path('generate_shipment/<str:pk>/', views.ShipOrder, name="generate_shipment"),
    path('sales_shipments/',ShipmentDashboardView.as_view(), name='sales-shipments'),
    path('view_shipment/<str:pk>/', views.viewShipment, name="view_shipment"),
    path('request_refund/<str:ref_code>/', views.RequestRefund, name="request_refund"),
    path('generate_refund/<str:pk>/', views.RefundOrder, name="generate_refund"),
    path('sales_refunds/',RefundDashboardView.as_view(), name='sales-refunds'),
    path('view_refund/<str:pk>/', views.viewRefund, name="view_refund"),
    path('view_items/', ViewItems.as_view(),name="view_items"),
    path('update_item/<str:pk>/', views.updateItem, name="update_item"),
    path('view_invoices/<str:ref_code>', views.viewInvoices, name="view_invoices"),
    path('view_shipments/<str:ref_code>', views.viewShipments, name="view_shipments"),
    path('view_refunds/<str:ref_code>', views.viewRefunds, name="view_refunds"),
    path('order_invoices/<str:ref_code>', views.viewInvoicesCustomers, name="order_invoices"),
    path('order_shipments/<str:ref_code>', views.viewShipmentsCustomers, name="order_shipments"),
    path('order_refunds/<str:ref_code>', views.viewRefundsCustomers, name="order_refunds"),
    path('customers/',ViewCustomers.as_view(), name='view-customers'),
    path('create_item/', views.createItem, name="create_item"),
]

djangoApp/store/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    DefaultHomeView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    BrandView,
    UserOrdersView,
    OrderDashboardView,
    InvoiceDashboardView,
    ShipmentDashboardView,
    RefundDashboardView,
    ViewItems,
    ViewCustomers
)

app_name = 'store'

urlpatterns = [
    path('', DefaultHomeView.as_view(), name='store-default-home'),
    path('<str:store_slug>/home', HomeView.as_view(), name='store-home'),
    path('<str:store_slug>/checkout/', CheckoutView.as_view(), name='checkout'),
    path('<str:store_slug>/order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('<str:store_slug>/product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('<str:store_slug>/add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('<str:store_slug>/add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('<str:store_slug>/remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('<str:store_slug>/remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('<str:store_slug>/payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('category/<str:slug>',CategoryView.as_view(), name='by_category'),
    path('orders/',UserOrdersView.as_view(), name='user-orders'),
    path('brand/<str:slug>',BrandView.as_view(), name='by_brand'),
    path('sales_orders/',OrderDashboardView.as_view(), name='sales-orders'),
    path('update_order/<str:pk>/', views.updateOrder, name="update_order"),
    path('generate_invoice/<str:pk>/', views.invoiceOrder, name="generate_invoice"),
    path('sales_invoices/',InvoiceDashboardView.as_view(), name='sales-invoices'),
    path('view_invoice/<str:pk>/', views.viewInvoice, name="view_invoice"),
    path('view_order_invoice/<str:ref_code>/', views.customerViewInvoice, name="customer_view_invoice"),
    path('generate_shipment/<str:pk>/', views.ShipOrder, name="generate_shipment"),
    path('sales_shipments/',ShipmentDashboardView.as_view(), name='sales-shipments'),
    path('view_shipment/<str:pk>/', views.viewShipment, name="view_shipment"),
    path('request_refund/<str:ref_code>/', views.RequestRefund, name="request_refund"),
    path('generate_refund/<str:pk>/', views.RefundOrder, name="generate_refund"),
    path('sales_refunds/',RefundDashboardView.as_view(), name='sales-refunds'),
    path('view_refund/<str:pk>/', views.viewRefund, name="view_refund"),
    path('view_items/', ViewItems.as_view(),name="view_items"),
    path('update_item/<str:pk>/', views.updateItem, name="update_item"),
    path('view_invoices/<str:ref_code>', views.viewInvoices, name="view_invoices"),
    path('view_shipments/<str:ref_code>', views.viewShipments, name="view_shipments"),
    path('view_refunds/<str:ref_code>', views.viewRefunds, name="view_refunds"),
    path('order_invoices/<str:ref_code>', views.viewInvoicesCustomers, name="order_invoices"),
    path('order_shipments/<str:ref_code>', views.viewShipmentsCustomers, name="order_shipments"),
    path('order_refunds/<str:ref_code>', views.viewRefundsCustomers, name="order_refunds"),
    path('customers/',ViewCustomers.as_view(), name='view-customers'),
    path('create_item/', views.createItem, name="create_item"),
]

djangoApp/singleStore/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from localflavor.in_.forms import INStateSelect
from django.contrib.auth.models import User


LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

ITEM_STATUS_CHOICES = (
    ('Enabled','Enabled'),
    ('Disabled','Disabled'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

INVOICE_STATUS_CHOICES = (
    ('Not Invoiced','Not Invoiced'),
    ('Partial Invoice','Partial Invoice'),
    ('Invoice Complete','Invoice Complete'),
)

SHIPMENT_STATUS_CHOICES = (
    ('No Shipments','No Shipments'),
    ('Partial Shipment','Partial Shipment'),
    ('Shipment Complete', 'Shipment Complete'),
)

REFUND_REQUEST_CHOICES = (
    ('No Refunds Requested','No Refunds Requested'),
    ('Partial Refunds Requested','Partial Refunds Requested'),
    ('Full Refund Requested', 'Full Refunds Requested'),
)

REFUND_STATUS_CHOICES = (
    ('No Refunds Initiated','No Refunds Initiated'),
    ('Partial Refunds Initiated','Partial Refunds Initiated'),
    ('Full Refund Initiated', 'Full Refunds Initiated'),
)

REPLACEMENT_REQUEST_CHOICES = (
    ('No Replacements Requested','No Replacements Requested'),
    ('Partial Replacements Requested','Partial Replacements Requested'),
    ('Full Replacements Requested', 'Full Replacements Requested'),
)

REPLACEMENT_STATUS_CHOICES = (
    ('No Replacements Initiated','No Replacement Initiated'),
    ('Partial Replacement Initiated','Partial Replacement Initiated'),
    ('Full Replacement Initiated', 'Full Replacement Initiated'),
)

ORDER_STATUS_CHOICES = (
    ('Pending', 'Pending'),
    ('Processing', 'Processing'),
    ('Shipped', 'Shipped'),
    ('Delivered','Delivered'),
    ('Complete','Complete'),
    ('Cancelled','Cancelled'),
    ('On Hold','On Hold'),
    ('Dispute Raised','Dispute Raised'),
    ('Resolution in Process','Resolution in Process'),
    ('Dispute Resolved','Dispute Resolved'),
)

STATE_CHOICES = (
                 ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), 
                 ('Maharashtra', 'Maharashtra'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), 
                 ('Rajasthan', 'Rajasthan'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), 
                 ('Telangana', 'Telangana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), 
                 ('Bihar', 'Bihar'), ('CG', 'Chattisgarh'), ('Haryana', 'Haryana'), ('Jharkhand', 'Jharkhand'), 
                 ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), 
                 ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Sikkim', 'Sikkim'), 
                 ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), 
                 ('Andaman and Nicobar', 'Andaman and Nicobar'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), 
                 ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Lakshadweep', 'Lakshadweep'), ('Pondicherry', 'Pondicherry')
                )

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='user_profile',
                                on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    priority = models.IntegerField(blank=True, null=True)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,blank=True, null=True ,related_name='children')

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        unique_together = ('slug', 'parent',)

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' -> '.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('store:products_by_category',kwargs={
            'slug': self.slug
        })

# class Page(models.Model):
#     isEnabled = models.BooleanField(default=False)
#     title = models.CharField(max_length=50)
#     body = models.TextField()
#
#     def __str__(self):
#         return self.title

class Brand(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    priority = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:products_by_brand',kwargs={
            'slug': self.slug
        })

class TaxRate(models.Model):
    name = models.CharField(max_length=100)
    rate = models.FloatField()
    def __str__(self):
        return self.name


class Item(models.Model):
    title = models.CharField(max_length=100)
    status = models.CharField(max_length=10, choices=ITEM_STATUS_CHOICES, default='Enabled')
    SKU = models.CharField(max_length=20,blank=True, null=True)
    price = models.FloatField()
    HSN = models.CharField(max_length=20,blank=True, null=True)
    available_quantity = models.IntegerField(default=0)
    min_stock_quantity = models.IntegerField(default=0)
    Tax_Rate = models.ForeignKey(TaxRate,
                             on_delete=models.CASCADE,blank=True, null=True)
    category = models.ManyToManyField(Category)
    brand = models.ForeignKey(Brand,
                             on_delete=models.CASCADE, blank=True, null=True)
    discount_price = models.FloatField(blank=True, null=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True, null=True)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("store:product", kwargs={
            'slug': self.slug
        })
    def get_add_to_cart_url(self):
        return reverse("store:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("store:remove-from-cart", kwargs={
            'slug': self.slug
        })

class StoreFront(models.Model):
    name = models.CharField(max_length=200, unique=True)
    address_line1 = models.CharField(max_length=100, blank=True, null =True)
    address_line2 = models.CharField(max_length=100, blank=True, null =True)
    country = CountryField(multiple=False, blank=True, null =True)
    state = models.CharField(choices=STATE_CHOICES, max_length=50, blank=True, null =True)
    pin = models.CharField(max_length=100, blank=True, null =True)
    store_slug = models.SlugField(unique=True)

    def __str__(self):
        return f"{self.name}"

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='user_order_item',
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    invoiced_quantity = models.IntegerField(default=0)
    shipped_quantity = models.IntegerField(default=0)
    refund_quantity = models.IntegerField(default=0)
    refund_request_quantity = models.IntegerField(default=0)
    refund_reason = models.CharField(max_length=100,blank=True, null=True)
    replacement_quantity = models.IntegerField(default=0)
    replacement_request_quantity = models.IntegerField(default=0)
    replacement_reason = models.CharField(max_length=100,blank=True, null=True)

    def __str__(self):
        return f"{self.quantity} of {self.item.title} invoiced {self.invoiced_quantity} shipped {self.shipped_quantity} refund requested {self.refund_request_quantity}  refund initiated {self.refund_quantity}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    def get_tax_amount(self):
        return self.get_final_price() * self.item.Tax_Rate.rate/100

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='user_order',
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    #items = models.ForeignKey(OrderItem, on_delete=models.CASCADE, blank=True, null=True)
    start_date = models.DateTimeField(blank=True,null=True)
    ordered_date = models.DateTimeField(blank=True,null=True)
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(

djangoApp/singleStore/templates/singleStore/admin_sidenav.html
			<div class="menu">
				<ul>
					<li>
						<a href = "#"><i class="fas fa-tachometer-alt fa-2x"></i><p class="list-name mt-1 mb-0">DASHBOARD</p></a>
					</li>
					<li>
						<a href = "#"><i class="fas fa-money-bill-wave fa-2x"></i><p class="list-name mt-1 mb-0">SALES</p></a>
						<ul>
                                                        {% if perms.singleStore.view_order %}
								<li><a href = "{% url 'singleStore:sales-orders' %}">ORDERS</a></li>
                                                        {% endif %}
							{% if perms.singleStore.view_invoice %}
								<li><a href = "{% url 'singleStore:sales-invoices' %}">INVOICES</a></li>
							{% endif %}
							{% if perms.singleStore.view_shipment %}
								<li><a href = "{% url 'singleStore:sales-shipments' %}">SHIPMENTS</a></li>
							{% endif %}
							{% if perms.singleStore.view_refund %}
							<li><a href = "{% url 'singleStore:sales-refunds' %}">REFUNDS</a></li>
							{% endif %}
                                                        {% if perms.singleStore.view_payment %}
							<li><a href = "{% url 'singleStore:sales-refunds' %}">PAYMENTS </a></li>
                                                        {% endif %}
						</ul>
					</li>
					<li><a href = "#"><i class="fas fa-box fa-2x"></i><p class="list-name mt-1 mb-0">CATALOG</p></a>
						<ul>
                                                        {% if perms.singleStore.view_item %}
							<li><a href = "{% url 'singleStore:view_items' %}">PRODUCTS</a></li>
                                                        {% endif %}
                                                        {% if perms.singleStore.view_productAttributes %}
							<li><a href = "#">PRODUCT ATTRIBUTES</a></li>
                                                        {% endif %}
                                                        {% if perms.singleStore.view_category %}
							<li><a href = "#">CATEGORIES</a></li>
                                                        {% endif %}
                                                        {% if perms.singleStore.view_brand %}
							<li><a href = "#">BRANDS</a></li>
                                                        {% endif %}
						</ul>
					</li>
					<li><a href = "#"><i class="fas fa-address-book fa-2x"></i><p class="list-name mt-1 mb-0">CUSTOMERS</p></a>
						<ul>
                                                        {% if perms.auth.view_user %}
							<li><a href = "{% url 'singleStore:view-customers' %}">ALL CUSTOMERS</a></li>
							{% endif %}
							<li><a href = "#">CUSTOMER GROUPS</a></li>
						</ul>
					</li>
					<li><a href = "#"><i class="fas fa-bullhorn fa-2x"></i><p class="list-name mt-1 mb-0">MARKETING</p></a>
						<ul>
							<li><a href = "#">COUPONS</a></li>
							<li><a href = "#">COUPON USAGE</a></li>
						</ul>
					</li>
                                        <li><a href = "#"><i class="fas fa-store-alt fa-2x"></i><p class="list-name mt-1 mb-0">STORES</p></a>
                                                <ul>
                                                        <li><a href = "{% url 'singleStore:sales-orders' %}">STORE FRONTS</a></li>
                                                        <li><a href = "{% url 'singleStore:sales-invoices' %}">SOURCES</a></li>
                                                        <li><a href = "{% url 'singleStore:sales-shipments' %}">STOCKS</a></li>
                                                        <li><a href = "{% url 'singleStore:sales-refunds' %}">INVENTORY</a></li>
                                                </ul>
                                        </li>
                                        <li><a href = "#"><i class="fas fa-headset fa-2x"></i><p class="list-name mt-1 mb-0">SUPPORT DESK</p></a>
                                                <ul>
                                                        <li><a href = "{% url 'singleStore:sales-orders' %}">REFUND REQUESTS</a></li>
                                                        <li><a href = "{% url 'singleStore:sales-invoices' %}">REPLACEMENT REQUESTS</a></li>
                                                        <li><a href = "{% url 'singleStore:sales-shipments' %}">DISPUTES</a></li>
                                                        <li><a href = "{% url 'singleStore:sales-refunds' %}">FAILED PAYMENTS</a></li>
                                                </ul>
                                        </li>
                                        <li><a href = "#"><i class="fas fa-cogs fa-2x"></i><p class="list-name mt-1 mb-0">SETTINGS</p></a>
                                                <ul>
                                                        <li><a href = "#">THEMES</a></li>
                                                        <li><a href = "#">USERS</a></li>
                                                        <li><a href = "#">TAX RATES</a></li>
                                                </ul>
                                        </li>
                                        <li>
						<a href = "#"><i class="fas fa-book-open fa-2x"></i><p class="list-name mt-1 mb-0">HELP</p></a>
					</li>
		
				</ul>
			</div>

djangoApp/singleStore/templates/singleStore/user_orders.html
{% extends "singleStore/base.html" %}
{% block content %}
<div class="col-md-6 mb-4 mt-4">
    <h1 class="mb-3">All Orders ({{page_obj.paginator.count}})</h1>
    {% for order in orders %}
    {% if order.ordered %}
    <div class="card">
    <h4 class="d-flex justify-content-between align-items-center mt-4 mb-3 ml-3">
    <span class="text-bold">Order Number: {{order.ref_code}}</span>
    </h4>
    <h5 class="d-flex justify-content-between align-items-center mb-3 ml-3">
    <span class="text-bold">Order Date: {{order.ordered_date}}</span>
    </h5>
    <h5 class="d-flex justify-content-between align-items-center mb-3 ml-3">
    <span class="text-bold">Status: {{order.status}}</span>
    </h5>
    <div class = "row">
    <div class = "col-md-4">
    {% ifnotequal order.invoice_status "Not Invoiced" %}
    <h5 class="d-flex justify-content-between align-items-center ml-2 mb-3">
    <a href="{% url 'store:order_invoices' order.ref_code%}" class="btn btn-outline-info" role="button">View Invoices</a>
    </h5>
    {% endifnotequal %}
    </div>
    <div class = "col-md-6">
    {% if order.status == "Shipped" %}
    <h5 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-bold"><a href="{% url 'store:order_shipments' order.ref_code%}" class="btn btn-outline-info" role="button">View Shipments</a></span>
    </h5>
    {% endif %}
    </div>
    </div>
    <h5 class="d-flex justify-content-between align-items-center mb-3 ml-3">
    <span class="text-bold">Order Details</span>
    </h5>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        </div>
        <span class="text-muted">₹{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between">
        <h6 class="my-0">GST (INR)</h6>
        <span class="text-muted">₹{{ order.get_total_tax }}</span>
    </li>
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-₹{{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (INR)</span>
        <strong>₹{{ order.get_total }}</strong>
    </li>
    </ul>
    <div class = "row">
    <div class = "col-md-4">
    <h5 class="d-flex justify-content-between align-items-center ml-2 mb-3">
    <span class="text-bold"><a href = "{% url 'store:request_refund' order.ref_code %}" class="btn btn-outline-info" role="button">Refunds</a></span>
    </h5>
    </div>
    {% ifnotequal order.shipping_status "No Shipments" %}
    <div class = "col-md-4">
    <h5 class="d-flex justify-content-between align-items-center ml-2 mb-3">
    <span class="text-bold"><a href = "{% url 'store:request_refund' order.ref_code %}" class="btn btn-outline-info" role="button">Replacement</a></span>
    </h5>
    </div>
    {% endifnotequal %}
    </div>    
    {% if order.status == "Pending" %}
    <div class = "row">
    <div class = "col-md-4">
    <h5 class="d-flex justify-content-between align-items-center ml-2 mb-3">
    <span class="text-bold"><a href = "{% url 'store:request_refund' order.ref_code %}" class="btn btn-outline-danger" role="button">Report Issue</a></span>
    </h5>
    </div>
    <div class = "col-md-4">
    <h5 class="d-flex justify-content-between align-items-center ml-2 mb-3">
    <span class="text-bold"><a href = "{% url 'store:request_refund' order.ref_code %}" class="btn btn-outline-danger" role="button">Cancel Order</a></span>
    </h5>
    </div>
    </div>
    {% endif %}
    </div>


    {% else %}
    <h4 class="d-flex justify-content-between align-items-center mt-4 mb-3">
    <span class="text-bold">Order in Cart</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        </div>
        <span class="text-muted">₹{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-₹{{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (INR)</span>
        <strong>₹{{ order.get_total }}</strong>
    </li>
    </ul>
    {% endif %}
    <hr>
    {% endfor %}
</div>

{% endblock %}